run without root

diff --git a/run_onchange_bootstrap.sh.tmpl b/run_onchange_bootstrap.sh.tmpl
--- a/run_onchange_bootstrap.sh.tmpl
+++ b/run_onchange_bootstrap.sh.tmpl
@@ -1,9 +1,61 @@
 #!/bin/bash
+# .local/bootstrap/setup.yml hash: {{ include "dot_local/bootstrap/setup.yml" | sha256sum }}
 
-# .bootstrap/setup.yml hash: {{ include "dot_local/bootstrap/setup.yml" | sha256sum }}
 
-if command -v ansible-playbook &> /dev/null; then
-    ansible-playbook {{ joinPath .chezmoi.sourceDir "dot_local/bootstrap/setup.yml" | quote }} --ask-become-pass
+#
+# install ansible
+if ! command -v ansible-playbook &> /dev/null
+then
+  echo "Ansible is missing, install ilt ..."
+  install_on_fedora() {
+    sudo dnf install -y ansible
+  }
+
+  install_on_ubuntu() {
+    sudo apt-get update
+    sudo apt-get install -y ansible
+  }
+
+  install_on_mac() {
+    brew install ansible python3-apt
+  }
+
+  OS="$(uname -s)"
+  case "${OS}" in
+      Linux*)
+          if [ -f /etc/fedora-release ]; then
+              install_on_fedora
+          elif [ -f /etc/lsb-release ]; then
+              install_on_ubuntu
+          else
+              echo "Unsupported Linux distribution"
+              exit 1
+          fi
+          ;;
+      Darwin*)
+          install_on_mac
+          ;;
+      *)
+          echo "Unsupported operating system: ${OS}"
+          exit 1
+          ;;
+  esac
+
+  echo "Ansible installation complete."
 fi
 
+if ! command -v ansible-playbook &> /dev/null
+then
+  echo "Failed, missing ansible-playbook command"
+  exit 2
+fi
 
+#
+# run bootstrap playbook
+export ANSIBLE_HOST_KEY_CHECKING=False
+export ANSIBLE_NOCOWS=1
+export ANSIBLE_TIMEOUT=10 
+export ANSIBLE_SSH_TIMEOUT=10
+export ANSIBLE_TASK_TIMEOUT
+export ANSIBLE_STDOUT_CALLBACK=debug
+ansible-playbook {{ joinPath .chezmoi.sourceDir "dot_local/bootstrap/setup.yml" | quote }} --inventory localhost, --connection=local
